Controllers/numberPartsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Labels_KM49.Data;
using Labels_KM49.Models;
using Labels_KM49.Models.ViewModels;
using System.Net.NetworkInformation;
using System.Linq.Dynamic;
using System.ComponentModel.DataAnnotations;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;
namespace Labels_KM49.Controllers
{
    public class numberPartsController : Controller
    {
        private readonly ModelContext _context;

        public numberPartsController(ModelContext context)
        {
            _context = context;
        }

        // GET: numberParts
        public async Task<IActionResult> Index()
        {
            var time = DateTime.Now;

            IQueryable<JTransferspacketViewModel> 
            query = (from d in _context.JTransferspackets
            select new JTransferspacketViewModel
            {
                TspId = d.TspId,
                TspTcreation = d.TspTcreation,
                TspStatus = d.TspStatus,
                TspData = d.TspData

            });

            if (Request.ContentType != null)
            {
                var daysPost = Request.Form["days"].FirstOrDefault();
                var entriesPost = Request.Form["entries"].FirstOrDefault();
                var search = Request.Form["search"].FirstOrDefault();
                int days = 1;
                Int32.TryParse(daysPost, out days);
                int entries = 1;
                Int32.TryParse(entriesPost, out entries);

                if (search != "") query = query.Where(x => x.TspData.Contains(search));
                //if (search.Contains("*")) queryGenerator(search);
                query = query.Where(x => x.TspTcreation > time.AddDays(-days));
                ViewBag.recordsTotal = query.Count();

                return View(await query.OrderByDescending(m => m.TspTcreation).Take(entries).ToListAsync());
            }
            else
            {
                query = query.Where(x => x.TspTcreation > time.AddDays(-1));

                ViewBag.recordsTotal = query.Count();
                return View(await query.OrderByDescending(m => m.TspTcreation).Take(10).ToListAsync());
            }
            
        }

        private static string queryGenerator(string search)
        {
            string consulta = "";
            //Get list
            var plus = "&&";
            string[] filters = search.Split('*', StringSplitOptions.RemoveEmptyEntries);


            // Generar consulta 
            int cnt = filters.Length;

            for (int i = 0; i <= filters.Count(); i++)
            {
                string initFilter = "filters[" + i + "] ";
                consulta = "(x => x.TspData.Contains(" + filters[0] + ") )";
            }

            return consulta;
        }

    }
}

Views/numberParts/Create.cshtml
@model Labels_KM49.Models.JTransferspacket

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>JTransferspacket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TspId" class="control-label"></label>
                <input asp-for="TspId" class="form-control" />
                <span asp-validation-for="TspId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspConnectionId" class="control-label"></label>
                <select asp-for="TspConnectionId" class ="form-control" asp-items="ViewBag.TspConnectionId"></select>
            </div>
            <div class="form-group">
                <label asp-for="TspTimetransferred" class="control-label"></label>
                <input asp-for="TspTimetransferred" class="form-control" />
                <span asp-validation-for="TspTimetransferred" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspExternalname" class="control-label"></label>
                <input asp-for="TspExternalname" class="form-control" />
                <span asp-validation-for="TspExternalname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspQualifier1" class="control-label"></label>
                <input asp-for="TspQualifier1" class="form-control" />
                <span asp-validation-for="TspQualifier1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspQualifier2" class="control-label"></label>
                <input asp-for="TspQualifier2" class="form-control" />
                <span asp-validation-for="TspQualifier2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspStatus" class="control-label"></label>
                <input asp-for="TspStatus" class="form-control" />
                <span asp-validation-for="TspStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspPrevstatus" class="control-label"></label>
                <input asp-for="TspPrevstatus" class="form-control" />
                <span asp-validation-for="TspPrevstatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspData" class="control-label"></label>
                <input asp-for="TspData" class="form-control" />
                <span asp-validation-for="TspData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspTransferrefno" class="control-label"></label>
                <input asp-for="TspTransferrefno" class="form-control" />
                <span asp-validation-for="TspTransferrefno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/numberParts/Delete.cshtml
@model Labels_KM49.Models.JTransferspacket

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>JTransferspacket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspTcreation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspTcreation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspTimetransferred)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspTimetransferred)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspExternalname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspExternalname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspQualifier1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspQualifier1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspQualifier2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspQualifier2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspPrevstatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspPrevstatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspTransferrefno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspTransferrefno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspConnection)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspConnection.TcId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TspId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/numberParts/Details.cshtml
@model Labels_KM49.Models.JTransferspacket

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>JTransferspacket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspTcreation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspTcreation)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspTimetransferred)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspTimetransferred)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspExternalname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspExternalname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspQualifier1)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspQualifier1)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspQualifier2)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspQualifier2)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspPrevstatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspPrevstatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspData)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspData)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspTransferrefno)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspTransferrefno)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TspConnection)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TspConnection.TcId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.TspId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/numberParts/Edit.cshtml
@model Labels_KM49.Models.JTransferspacket

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>JTransferspacket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TspId" />
            <div class="form-group">
                <label asp-for="TspConnectionId" class="control-label"></label>
                <select asp-for="TspConnectionId" class="form-control" asp-items="ViewBag.TspConnectionId"></select>
                <span asp-validation-for="TspConnectionId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspTcreation" class="control-label"></label>
                <input asp-for="TspTcreation" class="form-control" />
                <span asp-validation-for="TspTcreation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspTimetransferred" class="control-label"></label>
                <input asp-for="TspTimetransferred" class="form-control" />
                <span asp-validation-for="TspTimetransferred" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspExternalname" class="control-label"></label>
                <input asp-for="TspExternalname" class="form-control" />
                <span asp-validation-for="TspExternalname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspQualifier1" class="control-label"></label>
                <input asp-for="TspQualifier1" class="form-control" />
                <span asp-validation-for="TspQualifier1" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspQualifier2" class="control-label"></label>
                <input asp-for="TspQualifier2" class="form-control" />
                <span asp-validation-for="TspQualifier2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspStatus" class="control-label"></label>
                <input asp-for="TspStatus" class="form-control" />
                <span asp-validation-for="TspStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspPrevstatus" class="control-label"></label>
                <input asp-for="TspPrevstatus" class="form-control" />
                <span asp-validation-for="TspPrevstatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspData" class="control-label"></label>
                <input asp-for="TspData" class="form-control" />
                <span asp-validation-for="TspData" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TspTransferrefno" class="control-label"></label>
                <input asp-for="TspTransferrefno" class="form-control" />
                <span asp-validation-for="TspTransferrefno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/numberParts/Index.cshtml
@model IEnumerable<Labels_KM49.Models.ViewModels.JTransferspacketViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-md">
    <h1>Filter & Split</h1>
    <h3 class="d-flex justify-content-end">Filters Options</h3>

    @* formulario section *@
    <form asp-controller="numberParts" asp-action="Index" method="post">
        <div class="d-flex justify-content-end p-2 m-2">
            <div class="m-2">
                <label>Entries</label>
            </div>
            <div>
                <select name="entries" class="form-select form-select-sm" aria-label="Small  select example">
                    <option selected>10</option>
                    <option value="50">50</option>
                    <option value="100">100</option>
                    <option value="300">300</option>
                </select>
            </div>
            <div class="m-2">
                <label>Days</label>
            </div>
            <div>

                <select name="days" class="form-select form-select-sm" aria-label="Small  select example">
                    <option selected>1</option>
                    <option value="10">10</option>
                    <option value="50">50</option>
                    <option disabled>Alert slow load!</option>
                    <option value="150">150 </option>
                    <option value="200">200</option>
                    <option value="365">365</option>
                </select>
            </div>
            <div class="m-2">
                <label>Filter</label>
            </div>
            <div>
                <input name="search" class="form-control form-control-sm" type="text" placeholder="Search" aria-label=".form-control-sm example">
            </div>
            <div>
                <button type="submit" class="btn btn-dark btn-sm ">Show me!</button>
            </div>
        </div>
    </form>

    @* DataTable section *@
    <div class="table-responsive mt-4">
        <table id="customerDatatable" class="table dt-responsive nowrap" width="100%" cellspacing="0">
            <thead>
                <tr>
                    <th>
                        Split!
                    </th>
                    <th>
                        Creation
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Data
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <!-- Button trigger modal -->
                            <button id="btn_split" type="button" class="btn_split btn btn-outline-dark" data-bs-toggle="modal" data-bs-target="#exampleModal" data-valor="@item.TspData">
                                Split!
                            </button>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TspTcreation)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TspStatus)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TspData)
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    @* Modal Container*@
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Split Tool</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div id="valoresCortados"></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>

    @* Pagination section *@
    <div class="d-flex justify-content-end">
        <div class="p-2 m-2">
            1 de @ViewBag.recordsTotal
        </div>

        <div class="m-2">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>

                    <li class="page-item">
                        <a class="page-link" href="#" aria-label="Next">
                            <span aria-hidden="true">&raquo;></span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</div>


@*Scripts Seccion*@
@section Scripts
{
    <script>
        $(document).ready(function () {
            $('.btn_split').click(function () {
                var valorBoton = $(this).data('valor');
                var valoresCortados = valorBoton.split(' ')/* .join(',').split('001').join(',').split('002') */.join(',').split('0000').join(',').split('.').join(',').split(',').filter(valor => valor !== "");
                var listaHTML = "<ul class='list-group list-group-flush'>";
                valoresCortados.forEach(function (valor) {
                    listaHTML += "<li class='list-group-item'>" + valor + "</li>";
                });
                listaHTML += "</ul>";
                $('#valoresCortados').html(listaHTML);
            });
        });
    </script>
}